export const LogoLight = require("../assets/images/Light-Logo.png")
export const LogoDark = require("../assets/images/Dark-Logo.png")
export const FbLight = require("../assets/images/fb-light.png")
export const FbDark = require("../assets/images/fb-dark.png")
export const GLight = require("../assets/images/g-light.png")
export const GDark = require("../assets/images/g-dark.png")
export const Banner = require("../assets/images/Banner.jpg")
export const Phone = require("../assets/images/Phone.png")
export const RArrow = require("../assets/images/right-arrow-black.png")
export const RArrowWhite = require("../assets/images/right-arrow.png")
export const LArrowWhite = require("../assets/images/left-arrow.png")
export const Money = require("../assets/images/money.png")
export const EMI = require("../assets/images/EMI.png")
export const Interest = require("../assets/images/Interest.png")
export const Down = require("../assets/images/Down.png")

